---
- name: Skyeng test task part 3
  connection: network_cli
  hosts: localhost
  vars:
    http_port: 2080
    ssh_port: 2022
    image_name: skyeng
    container_name: skyeng
  tasks:
  - name: Remove container if exists
    docker_container:
      name: skyeng
      state: absent
  - name: Remove image if exists
    docker_image:
      name: skyeng
      state: absent
  - name: Build image
    docker_image:
      name: skyeng
      path: ./
  - name: Start container
    docker_container:
      name: skyeng
      image: skyeng
      command: /docker_exec.sh
      state: started
      published_ports:
        - "{{ http_port }}:80"
        - "{{ ssh_port }}:22"
